In [1]:
import seaborn as sns
import numpy as np
import scipy.stats as stats


In [2]:
import pandas as pd


In [3]:
dataset = sns.load_dataset('tips')

In [4]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
dataset_table = pd.crosstab(dataset['sex'],dataset['smoker'])

In [6]:
dataset_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [7]:
obs_val = dataset_table.values

In [8]:
obs_val

array([[60, 97],
       [33, 54]])

In [9]:
val = stats.chi2_contingency(dataset_table)

In [10]:
val

(0.008763290531773594, 0.925417020494423, 1, array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [11]:
expected_value = val[3]

In [12]:
expected_value

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [14]:
num_of_rows = dataset_table.shape[0]

In [15]:
num_of_rows

2

In [16]:
num_of_cols = dataset_table.shape[1]

In [17]:
num_of_cols

2

In [18]:
dof = (num_of_rows-1)*(num_of_cols-1)

In [19]:
dof

1

In [20]:
alpha = 0.05

In [21]:
from scipy.stats import chi2

In [30]:
[(o,e) for o,e in zip(obs_val,expected_value)]

[(array([60, 97]), array([59.84016393, 97.15983607])),
 (array([33, 54]), array([33.15983607, 53.84016393]))]

In [22]:
chi_sqre = sum([(o-e)**2./e for o,e in zip(obs_val,expected_value)])


In [23]:
chi_sqre

array([0.00119737, 0.00073745])

In [24]:
chi_sqre_stat = chi_sqre[0] + chi_sqre[1]

In [25]:
chi_sqre_stat

0.001934818536627623

In [31]:
critical_val = chi2.ppf(q=1-alpha, df=dof)

In [32]:
critical_val

3.841458820694124

In [33]:
p_val  = 1 - chi2.cdf(x=chi_sqre_stat, df=dof)

In [34]:
p_val

0.964915107315732

In [35]:
if p_val <= alpha:
  print('Reject H0, There is a relationship between two categorical variable')
else:
  print('Retain H0, There is no relationship between two categorical variable')

Retain H0, There is no relationship between two categorical variable
