In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
dataset = pd.read_csv('/content/drive/MyDrive/AI/DL/Churn/Churn_Modelling.csv')

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
X = dataset.iloc[:,3:13]
X.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [5]:
y = dataset.iloc[:,13]
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [6]:
geography = pd.get_dummies(X['Geography'],drop_first=True)
geography

Germany  Spain
0           0      0
1           0      1
2           0      0
3           0      0
4           0      1
...       ...    ...
9995        0      0
9996        0      0
9997        0      0
9998        1      0
9999        0      0

[10000 rows x 2 columns]

In [7]:
gender=pd.get_dummies(X['Gender'],drop_first=True)
gender.head()

Male
0     0
1     0
2     0
3     0
4     0

In [8]:
X = pd.concat([X,geography,gender],axis=1)
X.head()

CreditScore Geography  Gender  Age  ...  EstimatedSalary  Germany  Spain  Male
0          619    France  Female   42  ...        101348.88        0      0     0
1          608     Spain  Female   41  ...        112542.58        0      1     0
2          502    France  Female   42  ...        113931.57        0      0     0
3          699    France  Female   39  ...         93826.63        0      0     0
4          850     Spain  Female   43  ...         79084.10        0      1     0

[5 rows x 13 columns]

In [9]:
X = X.drop(['Geography','Gender'],axis=1)
X.head()

CreditScore  Age  Tenure    Balance  ...  EstimatedSalary  Germany  Spain  Male
0          619   42       2       0.00  ...        101348.88        0      0     0
1          608   41       1   83807.86  ...        112542.58        0      1     0
2          502   42       8  159660.80  ...        113931.57        0      0     0
3          699   39       1       0.00  ...         93826.63        0      0     0
4          850   43       2  125510.82  ...         79084.10        0      1     0

[5 rows x 11 columns]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [12]:
X_train.shape , X_test.shape, y_train.shape, y_test.shape

((8000, 11), (2000, 11), (8000,), (2000,))

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
sc = StandardScaler()

In [15]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [16]:
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [17]:
X_test

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]])

In [18]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [19]:
classifier = Sequential()

In [20]:
classifier.add(Dense(units=6,kernel_initializer='he_uniform',activation='relu',input_dim=11))

In [21]:
classifier.add(Dropout(0.2))

In [22]:
classifier.add(Dense(units=6,kernel_initializer='he_uniform',activation='relu'))

In [23]:
classifier.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid'))

In [24]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 6)                 72        
_________________________________________________________________
dropout (Dropout)            (None, 6)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [25]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [26]:
model_history = classifier.fit(X_train,y_train,validation_split=0.33,batch_size=10,epochs=100)

Epoch 1/100
536/536 [==============================] - 2s 2ms/step - loss: 0.6585 - accuracy: 0.6917 - val_loss: 0.4810 - val_accuracy: 0.7895
Epoch 2/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4886 - accuracy: 0.7952 - val_loss: 0.4429 - val_accuracy: 0.8001
Epoch 3/100
536/536 [==============================] - 1s 1ms/step - loss: 0.4342 - accuracy: 0.8144 - val_loss: 0.4257 - val_accuracy: 0.8164
Epoch 4/100
536/536 [==============================] - 1s 1ms/step - loss: 0.4288 - accuracy: 0.8254 - val_loss: 0.4126 - val_accuracy: 0.8228
Epoch 5/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4234 - accuracy: 0.8277 - val_loss: 0.4027 - val_accuracy: 0.8357
Epoch 6/100
536/536 [==============================] - 1s 1ms/step - loss: 0.4266 - accuracy: 0.8175 - val_loss: 0.3968 - val_accuracy: 0.8353
Epoch 7/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3981 - accuracy: 0.8323 - val_loss: 0.3909 - val_accuracy: 0.8372

In [27]:
y_pred = classifier.predict(X_test)
y_pred

array([[0.31429416],
       [0.21941817],
       [0.10347039],
       ...,
       [0.1284369 ],
       [0.09213862],
       [0.23415956]], dtype=float32)

In [28]:
y_pred = (y_pred > 0.5)

In [29]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
cm = confusion_matrix(y_test,y_pred)

In [32]:
cm

array([[1578,   17],
       [ 267,  138]])

In [33]:
from sklearn.metrics import accuracy_score

In [34]:
accuracy_score(y_pred,y_test)

0.858