In [7]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [8]:
tf.keras.activations.deserialize('linear')


<function tensorflow.python.keras.activations.linear>

In [9]:
tf.keras.activations.deserialize('sigmoid')

<function tensorflow.python.keras.activations.sigmoid>

In [15]:
model = keras.Sequential([layers.Dense(2,activation='relu',name='layer1'),layers.Dense(3,activation='relu',name='layer2'),layers.Dense(4,activation='relu',name='layer3')])

In [16]:
x = tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [17]:
y = model(x)
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.64748347, 0.        , 0.        , 0.        ],
       [0.64748347, 0.        , 0.        , 0.        ],
       [0.64748347, 0.        , 0.        , 0.        ]], dtype=float32)>

In [19]:
layer1 = layers.Dense(2,activation='relu',name='layer1')
layer2 = layers.Dense(3,activation='relu',name='layer2')
layer3 = layers.Dense(4,activation='relu',name='layer3')

y = layer3(layer2(layer1(x)))
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.        , 0.23026834, 0.31668815, 0.        ],
       [0.        , 0.23026834, 0.31668815, 0.        ],
       [0.        , 0.23026834, 0.31668815, 0.        ]], dtype=float32)>

In [20]:
model.layers